# Generated by Django 2.0.4 on 2018-05-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0002_auto_20180511_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='fingerprint',
        ),
        migrations.AlterField(
            model_name='issue',
            name='groupId',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
