# Generated by Django 2.0.4 on 2018-05-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0003_auto_20180525_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='groupId',
            new_name='group_id',
        ),
    ]
