# Generated by Django 2.0.4 on 2018-05-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0004_auto_20180525_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.TextField(default='', max_length=255),
        ),
    ]
